# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chissl < Formula
  desc "HTTPS reverse tunnel server/client"
  homepage "https://github.com/NextChapterSoftware/chissl"
  version "1.1"
  license "MIT"

  on_macos do
    url "https://github.com/NextChapterSoftware/chissl/releases/download/v1.1/chissl_Darwin_all.zip"
    sha256 "e48149ced20d2a4c52b4dfada6d22f3438dc0d2bfc770785e639d5ae4c2f9992"

    def install
      bin.install "chissl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NextChapterSoftware/chissl/releases/download/v1.1/chissl_Linux_x86_64.zip"
        sha256 "30034eac7b6441bfeccdd9bde3fed36047f3e73b5f12bce6ee29f5da58575eb6"

        def install
          bin.install "chissl"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/NextChapterSoftware/chissl/releases/download/v1.1/chissl_Linux_armv6.zip"
        sha256 "f06c7d452567fa408b24246987b54ef61afc1f59a2efe0f0eab77503c0b7357d"

        def install
          bin.install "chissl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NextChapterSoftware/chissl/releases/download/v1.1/chissl_Linux_arm64.zip"
        sha256 "5c0953f4664cb2ad2742dbc67448b27b28967fc3a354703f59dade75a9fe2e75"

        def install
          bin.install "chissl"
        end
      end
    end
  end
end
